Completed javascript-timers
CTMendoza/m2-1222-code-solutions pull request #6
Opened 2022-12-10 19:52 UTC by CTMendoza

![javascript-timers](https://user-images.githubusercontent.com/90743100/206872951-fc8ed2e5-72d8-43c0-9fb4-8274979d0f9c.gif)

2022-12-13 03:39 UTC, TimelikeClosure requested changes

2022-12-13 03:39 UTC, TimelikeClosure commented on javascript-timers/interval.js
> +var intervalId = setInterval($changeH1Text, 1000);
You should be able to solve this by only setting one interval, not two intervals.

2022-12-13 07:01 UTC, CTMendoza commented
![javascript-timers](https://user-images.githubusercontent.com/90743100/207248297-6f4d15ae-617e-4a6b-acc9-326250bda7cd.gif)

2022-12-14 00:55 UTC, TimelikeClosure approved these changes

2022-12-14 19:37 UTC, merged